apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: secretvolume
    secret:
      secretName: sample-secret3
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: secretvolume
      mountPath: /secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}