apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress_service.name }}
  labels:
    app: wordpress
spec:
  type: {{ .Values.wordpress_service.type }}
  ports:
    - port: {{ .Values.wordpress_service.port }}
      targetPort: {{ .Values.wordpress_service.tartgePort }}
      protocol: {{ .Values.wordpress_service.protocol }}
  selector:
    app: wordpress