apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  volumes:
  - name: share-data
    emptyDir: {}
  containers:
  - image: nginx:1.20.0
    name: nginx
    volumeMounts:
    - name: share-data
      mountPath: /usr/share/nginx/html
    resources: {}
  - name: work-container
    image: busybox
    volumeMounts:
    - name: share-data
      mountPath: /data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the work-container > /data/index.html;sleep 2400"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}