apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: DOCKERHUB_USER/practice-skaffold # 変更箇所 DOCKERHUB_USER
    docker:
      dockerfile: ./Dockerfile
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - practice-skaffold-*